name: family
description: family.
version: 1.0.0+1

environment:
  sdk: ^2.10.4
  flutter: ^1.22.4

dependencies:
  cached_network_image: ^2.4.1
  collection: ^1.14.13
  convert: ^2.1.1
  crypto: ^2.1.5
  cupertino_icons: ^1.0.0
  device_info: ^1.0.0
  dio: ^3.0.10
  fluro: ^1.7.7
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.6
  flutter_localizations:
    sdk: flutter
  fluttertoast: 7.1.6
  image_picker: ^0.6.7+12
  #  intl_translation: ^0.17.10+1
  #  intl: ^0.17.0
  json_annotation: ^3.1.0
  meta: ^1.2.3
  path: ^1.7.0
  path_provider: ^1.6.22
  package_info: ^0.4.3
  shared_preferences: ^0.5.12
  sqflite: ^1.3.2+1
  flutter_qr_reader: ^1.0.3
  permission_handler: ^3.0.0
  pull_to_refresh: 1.6.3
  uuid: ^2.2.2
  url_launcher: ^5.7.8
  webview_flutter: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  json_serializable: ^3.5.0
#  intl: "0.17.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
#  assets:
#    - assets/common/gif/


